<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Axis.Engine</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Axis.Collision/Axis.Collision.csproj" />
    <ProjectReference Include="../Axis.Core/Axis.Core.csproj" />
    <ProjectReference Include="../Axis.ECS/Axis.ECS.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Raylib-cs" Version="7.0.2" />
  </ItemGroup>

</Project>
