using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Axis.ECS.Generators;

[Generator]
public sealed class QueryGenerator : IIncrementalGenerator
{
    // Maximum number of component type parameters to generate.
    private const int MaxComponents = 8;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Only generate into the main Axis.ECS assembly to avoid
        // duplicate type definitions in referencing projects (e.g. tests).
        var assemblyNameProvider = context.CompilationProvider
            .Select((compilation, _) => compilation.AssemblyName);

        context.RegisterSourceOutput(assemblyNameProvider, static (spc, assemblyName) =>
        {
            if (!string.Equals(assemblyName, "Axis.ECS", StringComparison.Ordinal))
                return;

            var source = GenerateSource();
            spc.AddSource("QueryVariants.g.cs", SourceText.From(source, Encoding.UTF8));
        });
    }

    private static string GenerateSource()
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using System;");
        sb.AppendLine("using Axis.ECS;");
        sb.AppendLine("using Axis.ECS.Queries;");
        sb.AppendLine();
        sb.AppendLine("namespace Axis.ECS.Queries;");
        sb.AppendLine();

        EmitDefineQuery(sb);
        sb.AppendLine();

        for (int n = 1; n <= MaxComponents; n++)
        {
            EmitQueryType(sb, n);
            sb.AppendLine();
            EmitQueryBuilderType(sb, n);
            sb.AppendLine();
            EmitSystemRegistration(sb, n);
            sb.AppendLine();
            EmitSystemWrappers(sb, n);
            sb.AppendLine();
        }

        EmitWorldSystemExtensions(sb);

        return sb.ToString();
    }

    private static void EmitQueryType(StringBuilder sb, int componentCount)
    {
        var typeParams = string.Join(", ", Enumerable.Range(0, componentCount).Select(i => $"T{i}"));

        sb.AppendLine($"public readonly struct Query<{typeParams}>");
        for (int i = 0; i < componentCount; i++)
        {
            sb.AppendLine($"    where T{i} : unmanaged");
        }
        sb.AppendLine("{");
        sb.AppendLine("    private readonly ArchetypeQuery _archetypeQuery;");
        sb.AppendLine();
        sb.AppendLine("    internal Query(ArchetypeQuery archetypeQuery)");
        sb.AppendLine("    {");
        sb.AppendLine("        _archetypeQuery = archetypeQuery;");
        sb.AppendLine("    }");
        sb.AppendLine();

        // Iterate delegate: per-archetype span access. No Iter — caller iterates spans themselves
        // and uses ids[i] for entity Id.
        var iterateSpanParams = string.Join(", ", Enumerable.Range(0, componentCount)
            .Select(i => $"Span<T{i}> c{i}"));
        sb.AppendLine($"    public delegate void IterateArchetypesDelegate(Span<Id> ids, {iterateSpanParams});");

        // ForEach delegate: per-entity convenience.
        var forEachRefParams = string.Join(", ", Enumerable.Range(0, componentCount)
            .Select(i => $"ref T{i} c{i}"));
        sb.AppendLine($"    public delegate void ForEachDelegate(Entity entity, {forEachRefParams});");
        sb.AppendLine();

        // Iterate method
        sb.AppendLine("    public void Iterate(IterateArchetypesDelegate action)");
        sb.AppendLine("    {");
        sb.AppendLine("        var archetypes = _archetypeQuery.Run();");
        sb.AppendLine();
        sb.AppendLine("        foreach (Archetype archetype in archetypes)");
        sb.AppendLine("        {");
        sb.AppendLine("            var ids = archetype.GetEntityIds();");
        for (int i = 0; i < componentCount; i++)
        {
            sb.AppendLine($"            archetype.TryGetColumnSpan(out Span<T{i}> c{i});");
        }

        var iterateArgs = string.Join(", ", Enumerable.Range(0, componentCount).Select(i => $"c{i}"));
        sb.AppendLine($"            action(ids, {iterateArgs});");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();

        // ForEach method
        sb.AppendLine("    public void ForEach(ForEachDelegate action)");
        sb.AppendLine("    {");
        sb.AppendLine("        var archetypes = _archetypeQuery.Run();");
        sb.AppendLine();
        sb.AppendLine("        foreach (Archetype archetype in archetypes)");
        sb.AppendLine("        {");
        sb.AppendLine("            World world = archetype.World;");
        sb.AppendLine("            var entityIds = archetype.GetEntityIds();");
        for (int i = 0; i < componentCount; i++)
        {
            sb.AppendLine($"            archetype.TryGetColumnSpan(out Span<T{i}> c{i});");
        }
        sb.AppendLine();
        sb.AppendLine("            for (int i = 0; i < c0.Length; i++)");
        sb.AppendLine("            {");
        sb.AppendLine("                var entity = Entity.Create(world, entityIds[i]);");

        var forEachArgs = string.Join(string.Empty, Enumerable.Range(0, componentCount)
            .Select(i => $", ref c{i}[i]"));
        sb.AppendLine($"                action(entity{forEachArgs});");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine("    }");

        sb.AppendLine("}");
    }

    private static void EmitQueryBuilderType(StringBuilder sb, int componentCount)
    {
        var typeParams = string.Join(", ", Enumerable.Range(0, componentCount).Select(i => $"T{i}"));

        sb.AppendLine($"public struct QueryBuilder<{typeParams}>");
        for (int i = 0; i < componentCount; i++)
        {
            sb.AppendLine($"    where T{i} : unmanaged");
        }
        sb.AppendLine("{");
        sb.AppendLine("    private QueryBuilder _builder;");
        sb.AppendLine();
        sb.AppendLine("    internal QueryBuilder(QueryBuilder builder)");
        sb.AppendLine("    {");
        sb.AppendLine("        _builder = builder;");
        sb.AppendLine("    }");
        sb.AppendLine();

        var typeArgs = string.Join(", ", Enumerable.Range(0, componentCount).Select(i => $"T{i}"));
        sb.AppendLine($"    public Query<{typeArgs}> Build()");
        sb.AppendLine("    {");
        sb.AppendLine("        var query = _builder.Build();");
        sb.AppendLine($"        return new Query<{typeArgs}>(query);");
        sb.AppendLine("    }");
        sb.AppendLine("}");
    }

    private static void EmitSystemRegistration(StringBuilder sb, int componentCount)
    {
        var typeParams = string.Join(", ", Enumerable.Range(0, componentCount).Select(i => $"T{i}"));
        var typeArgs = typeParams;

        sb.AppendLine($"public readonly struct SystemRegistration<{typeParams}>");
        for (int i = 0; i < componentCount; i++)
        {
            sb.AppendLine($"    where T{i} : unmanaged");
        }
        sb.AppendLine("{");
        sb.AppendLine("    private readonly World _world;");
        sb.AppendLine($"    private readonly Query<{typeArgs}> _query;");
        sb.AppendLine();
        sb.AppendLine($"    internal SystemRegistration(World world, Query<{typeArgs}> query)");
        sb.AppendLine("    {");
        sb.AppendLine("        _world = world;");
        sb.AppendLine("        _query = query;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    public void ForEach(Query<{typeArgs}>.ForEachDelegate action)");
        sb.AppendLine("    {");
        sb.AppendLine($"        var system = new SystemForEachWrapper<{typeArgs}>(_query, action);");
        sb.AppendLine("        WorldExtensions.AddSystem(_world, system);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    public void Iterate(Query<{typeArgs}>.IterateArchetypesDelegate action)");
        sb.AppendLine("    {");
        sb.AppendLine($"        var system = new SystemIterateWrapper<{typeArgs}>(_query, action);");
        sb.AppendLine("        WorldExtensions.AddSystem(_world, system);");
        sb.AppendLine("    }");
        sb.AppendLine("}");
    }

    private static void EmitSystemWrappers(StringBuilder sb, int componentCount)
    {
        var typeParams = string.Join(", ", Enumerable.Range(0, componentCount).Select(i => $"T{i}"));
        var typeArgs = typeParams;

        // ForEach wrapper
        sb.AppendLine($"internal sealed class SystemForEachWrapper<{typeParams}> : IWorldSystem");
        for (int i = 0; i < componentCount; i++)
        {
            sb.AppendLine($"    where T{i} : unmanaged");
        }
        sb.AppendLine("{");
        sb.AppendLine($"    private readonly Query<{typeArgs}> _query;");
        sb.AppendLine($"    private readonly Query<{typeArgs}>.ForEachDelegate _action;");
        sb.AppendLine();
        sb.AppendLine($"    internal SystemForEachWrapper(Query<{typeArgs}> query, Query<{typeArgs}>.ForEachDelegate action)");
        sb.AppendLine("    {");
        sb.AppendLine("        _query = query;");
        sb.AppendLine("        _action = action;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    public void Execute(ref WorldSystemContext context)");
        sb.AppendLine("    {");
        sb.AppendLine("        _query.ForEach(_action);");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();

        // Iterate wrapper
        sb.AppendLine($"internal sealed class SystemIterateWrapper<{typeParams}> : IWorldSystem");
        for (int i = 0; i < componentCount; i++)
        {
            sb.AppendLine($"    where T{i} : unmanaged");
        }
        sb.AppendLine("{");
        sb.AppendLine($"    private readonly Query<{typeArgs}> _query;");
        sb.AppendLine($"    private readonly Query<{typeArgs}>.IterateArchetypesDelegate _action;");
        sb.AppendLine();
        sb.AppendLine($"    internal SystemIterateWrapper(Query<{typeArgs}> query, Query<{typeArgs}>.IterateArchetypesDelegate action)");
        sb.AppendLine("    {");
        sb.AppendLine("        _query = query;");
        sb.AppendLine("        _action = action;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    public void Execute(ref WorldSystemContext context)");
        sb.AppendLine("    {");
        sb.AppendLine("        _query.Iterate(_action);");
        sb.AppendLine("    }");
        sb.AppendLine("}");
    }

    private static void EmitWorldSystemExtensions(StringBuilder sb)
    {
        sb.AppendLine("public static class WorldSystemExtensions");
        sb.AppendLine("{");

        for (int componentCount = 1; componentCount <= MaxComponents; componentCount++)
        {
            var typeParams = string.Join(", ", Enumerable.Range(0, componentCount).Select(i => $"T{i}"));
            var whereClauses = string.Join(" ", Enumerable.Range(0, componentCount).Select(i => $"where T{i} : unmanaged"));

            sb.AppendLine($"    public static SystemRegistration<{typeParams}> System<{typeParams}>(this IWorld world) {whereClauses}");
            sb.AppendLine("    {");
            sb.AppendLine("        var concrete = (World)world;");
            sb.AppendLine("        var builder = QueryBuilder.For(concrete);");
            for (int i = 0; i < componentCount; i++)
            {
                sb.AppendLine($"        builder.Add<T{i}>();");
            }
            sb.AppendLine("        var archetypeQuery = builder.Build();");
            sb.AppendLine($"        var typedQuery = new Query<{typeParams}>(archetypeQuery);");
            sb.AppendLine($"        return new SystemRegistration<{typeParams}>(concrete, typedQuery);");
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        sb.AppendLine("}");
    }

    private static void EmitDefineQuery(StringBuilder sb)
    {
        sb.AppendLine("public static partial class DefineQuery");
        sb.AppendLine("{");

        for (int componentCount = 1; componentCount <= MaxComponents; componentCount++)
        {
            var typeParams = string.Join(", ", Enumerable.Range(0, componentCount).Select(i => $"T{i}"));
            var whereClauses = string.Join(" ", Enumerable.Range(0, componentCount).Select(i => $"where T{i} : unmanaged"));

            sb.AppendLine($"    public static QueryBuilder<{typeParams}> For<{typeParams}>(IWorld world) {whereClauses}");
            sb.AppendLine("    {");
            sb.AppendLine("        var concrete = (World)world;");
            sb.AppendLine("        var builder = QueryBuilder.For(concrete);");
            for (int i = 0; i < componentCount; i++)
            {
                sb.AppendLine($"        builder.Add<T{i}>();");
            }
            sb.AppendLine($"        return new QueryBuilder<{typeParams}>(builder);");
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        sb.AppendLine("}");
    }
}
