using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Axis.ECS.Generators;

[Generator]
public sealed class QueryGenerator : IIncrementalGenerator
{
    // Maximum number of component type parameters to generate.
    private const int MaxComponents = 8;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Only generate into the main Axis.ECS assembly to avoid
        // duplicate type definitions in referencing projects (e.g. tests).
        var assemblyNameProvider = context.CompilationProvider
            .Select((compilation, _) => compilation.AssemblyName);

        context.RegisterSourceOutput(assemblyNameProvider, static (spc, assemblyName) =>
        {
            if (!string.Equals(assemblyName, "Axis.ECS", StringComparison.Ordinal))
                return;

            var source = GenerateSource();
            spc.AddSource("QueryVariants.g.cs", SourceText.From(source, Encoding.UTF8));
        });
    }

    private static string GenerateSource()
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using System;");
        sb.AppendLine("namespace Axis.ECS.Queries;");
        sb.AppendLine();

        // Generate DefineQuery helpers for all arities.
        EmitDefineQuery(sb);
        sb.AppendLine();

        for (int n = 1; n <= MaxComponents; n++)
        {
            EmitQueryType(sb, n);
            sb.AppendLine();
            EmitQueryBuilderType(sb, n);
            sb.AppendLine();
        }

        return sb.ToString();
    }

    private static void EmitQueryType(StringBuilder sb, int componentCount)
    {
        // Build generic type parameters: T0, T1, ..., T{n-1}
        var typeParams = string.Join(", ", Enumerable.Range(0, componentCount).Select(i => $"T{i}"));

        sb.AppendLine($"public readonly struct Query<{typeParams}>");
        for (int i = 0; i < componentCount; i++)
        {
            sb.AppendLine($"    where T{i} : unmanaged");
        }
        sb.AppendLine("{");
        sb.AppendLine("    private readonly ArchetypeQuery _archetypeQuery;");
        sb.AppendLine();
        sb.AppendLine("    internal Query(ArchetypeQuery archetypeQuery)");
        sb.AppendLine("    {");
        sb.AppendLine("        _archetypeQuery = archetypeQuery;");
        sb.AppendLine("    }");
        sb.AppendLine();

        // Delegates
        var iterateParams = string.Join(", ", Enumerable.Range(0, componentCount)
            .Select(i => $"Span<T{i}> c{i}"));
        sb.AppendLine($"    public delegate void IterateArchetypesDelegate(Iter iter, {iterateParams});");

        var forEachParams = string.Join(", ", Enumerable.Range(0, componentCount)
            .Select(i => $"ref T{i} c{i}"));
        sb.AppendLine($"    public delegate void ForEachDelegate(Entity entity, {forEachParams});");
        sb.AppendLine();

        // Iterate method
        sb.AppendLine("    public void Iterate(IterateArchetypesDelegate action)");
        sb.AppendLine("    {");
        sb.AppendLine("        var archetypes = _archetypeQuery.Run();");
        sb.AppendLine();
        sb.AppendLine("        foreach (Archetype archetype in archetypes)");
        sb.AppendLine("        {");
        sb.AppendLine("            var iter = new Iter(archetype);");
        for (int i = 0; i < componentCount; i++)
        {
            sb.AppendLine($"            archetype.TryGetColumnSpan(out Span<T{i}> c{i});");
        }

        var iterateArgs = string.Join(", ", Enumerable.Range(0, componentCount).Select(i => $"c{i}"));
        sb.AppendLine($"            action(iter, {iterateArgs});");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();

        // ForEach method
        sb.AppendLine("    public void ForEach(ForEachDelegate action)");
        sb.AppendLine("    {");
        sb.AppendLine("        var archetypes = _archetypeQuery.Run();");
        sb.AppendLine();
        sb.AppendLine("        foreach (Archetype archetype in archetypes)");
        sb.AppendLine("        {");
        sb.AppendLine("            World world = archetype.World;");
        sb.AppendLine("            var entityIds = archetype.GetEntityIds();");
        for (int i = 0; i < componentCount; i++)
        {
            sb.AppendLine($"            archetype.TryGetColumnSpan(out Span<T{i}> c{i});");
        }
        sb.AppendLine();
        sb.AppendLine("            for (int i = 0; i < c0.Length; i++)");
        sb.AppendLine("            {");
        sb.AppendLine("                var entity = Entity.Create(world, entityIds[i]);");

        var forEachArgs = string.Join(string.Empty, Enumerable.Range(0, componentCount)
            .Select(i => $", ref c{i}[i]"));
        sb.AppendLine($"                action(entity{forEachArgs});");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine("    }");

        sb.AppendLine("}");
    }

    private static void EmitQueryBuilderType(StringBuilder sb, int componentCount)
    {
        var typeParams = string.Join(", ", Enumerable.Range(0, componentCount).Select(i => $"T{i}"));

        sb.AppendLine($"public struct QueryBuilder<{typeParams}>");
        for (int i = 0; i < componentCount; i++)
        {
            sb.AppendLine($"    where T{i} : unmanaged");
        }
        sb.AppendLine("{");
        sb.AppendLine("    private QueryBuilder _builder;");
        sb.AppendLine();
        sb.AppendLine("    internal QueryBuilder(QueryBuilder builder)");
        sb.AppendLine("    {");
        sb.AppendLine("        _builder = builder;");
        sb.AppendLine("    }");
        sb.AppendLine();

        var typeArgs = string.Join(", ", Enumerable.Range(0, componentCount).Select(i => $"T{i}"));
        sb.AppendLine($"    public Query<{typeArgs}> Build()");
        sb.AppendLine("    {");
        sb.AppendLine("        var query = _builder.Build();");
        sb.AppendLine($"        return new Query<{typeArgs}>(query);");
        sb.AppendLine("    }");
        sb.AppendLine("}");
    }

    private static void EmitDefineQuery(StringBuilder sb)
    {
        sb.AppendLine("public static partial class DefineQuery");
        sb.AppendLine("{");

        for (int componentCount = 1; componentCount <= MaxComponents; componentCount++)
        {
            var typeParams = string.Join(", ", Enumerable.Range(0, componentCount).Select(i => $"T{i}"));
            var whereClauses = string.Join(" ", Enumerable.Range(0, componentCount).Select(i => $"where T{i} : unmanaged"));

            sb.AppendLine($"    public static QueryBuilder<{typeParams}> For<{typeParams}>(World world) {whereClauses}");
            sb.AppendLine("    {");
            sb.AppendLine("        var builder = QueryBuilder.For(world);");
            for (int i = 0; i < componentCount; i++)
            {
                sb.AppendLine($"        builder.Add<T{i}>();");
            }
            sb.AppendLine($"        return new QueryBuilder<{typeParams}>(builder);");
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        sb.AppendLine("}");
    }
}
