using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Axis.ECS.Generators;

[Generator]
public sealed class QueryGenerator : IIncrementalGenerator
{
    // Maximum number of component type parameters to generate.
    private const int MaxComponents = 8;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Only generate into the main Axis.ECS assembly to avoid
        // duplicate type definitions in referencing projects (e.g. tests).
        var assemblyNameProvider = context.CompilationProvider
            .Select((compilation, _) => compilation.AssemblyName);

        context.RegisterSourceOutput(assemblyNameProvider, static (spc, assemblyName) =>
        {
            if (!string.Equals(assemblyName, "Axis.ECS", StringComparison.Ordinal))
                return;

            var source = GenerateSource();
            spc.AddSource("QueryVariants.g.cs", SourceText.From(source, Encoding.UTF8));
        });
    }

    private static string GenerateSource()
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using System;");
        sb.AppendLine("using Axis.ECS;");
        sb.AppendLine("using Axis.ECS.Queries;");
        sb.AppendLine();
        sb.AppendLine("namespace Axis.ECS.Queries;");
        sb.AppendLine();

        EmitDefineQuery(sb);
        sb.AppendLine();

        for (int n = 0; n <= MaxComponents; n++)
        {
            EmitQueryType(sb, n);
            sb.AppendLine();
            EmitQueryBuilderType(sb, n);
            sb.AppendLine();

            if (n >= 1)
            {
                EmitSystemRegistration(sb, n);
                sb.AppendLine();
                EmitSystemWrappers(sb, n);
                sb.AppendLine();
            }
        }

        EmitWorldSystemExtensions(sb);

        return sb.ToString();
    }

    private static string GenericArgs(int componentCount)
    {
        if (componentCount == 0) return string.Empty;
        var typeParams = string.Join(", ", Enumerable.Range(0, componentCount).Select(i => $"T{i}"));
        return "<" + typeParams + ">";
    }

    private static void EmitWhereClauses(StringBuilder sb, int componentCount)
    {
        for (int i = 0; i < componentCount; i++)
        {
            sb.AppendLine($"    where T{i} : unmanaged");
        }
    }

    private static void EmitQueryType(StringBuilder sb, int componentCount)
    {
        var generics = GenericArgs(componentCount);

        sb.AppendLine($"public readonly struct Query{generics}");
        EmitWhereClauses(sb, componentCount);
        sb.AppendLine("{");
        sb.AppendLine("    private readonly ArchetypeQuery _archetypeQuery;");
        sb.AppendLine();
        sb.AppendLine($"    internal Query(ArchetypeQuery archetypeQuery)");
        sb.AppendLine("    {");
        sb.AppendLine("        _archetypeQuery = archetypeQuery;");
        sb.AppendLine("    }");
        sb.AppendLine();

        // Iterate delegate: per-archetype span access. Arity-0 yields just the entity-ids span.
        if (componentCount == 0)
        {
            sb.AppendLine("    public delegate void IterateArchetypesDelegate(Span<Id> ids);");
        }
        else
        {
            var iterateSpanParams = string.Join(", ", Enumerable.Range(0, componentCount)
                .Select(i => $"Span<T{i}> c{i}"));
            sb.AppendLine($"    public delegate void IterateArchetypesDelegate(Span<Id> ids, {iterateSpanParams});");
        }

        // ForEach delegate: per-entity convenience. Arity-0 yields just the Entity.
        if (componentCount == 0)
        {
            sb.AppendLine("    public delegate void ForEachDelegate(Entity entity);");
        }
        else
        {
            var forEachRefParams = string.Join(", ", Enumerable.Range(0, componentCount)
                .Select(i => $"ref T{i} c{i}"));
            sb.AppendLine($"    public delegate void ForEachDelegate(Entity entity, {forEachRefParams});");
        }
        sb.AppendLine();

        // Unregister: stop receiving invalidation when archetypes change
        sb.AppendLine("    public void Unregister()");
        sb.AppendLine("    {");
        sb.AppendLine("        _archetypeQuery.Unregister();");
        sb.AppendLine("    }");
        sb.AppendLine();

        // Count: entity count across matching archetypes
        sb.AppendLine("    public int Count() => _archetypeQuery.Count();");
        sb.AppendLine();

        // Iterate method
        sb.AppendLine("    public void Iterate(IterateArchetypesDelegate action)");
        sb.AppendLine("    {");
        sb.AppendLine("        var archetypes = _archetypeQuery.Run();");
        sb.AppendLine();
        sb.AppendLine("        foreach (Archetype archetype in archetypes)");
        sb.AppendLine("        {");
        sb.AppendLine("            var ids = archetype.GetEntityIds();");
        for (int i = 0; i < componentCount; i++)
        {
            sb.AppendLine($"            archetype.TryGetColumnSpan(out Span<T{i}> c{i});");
        }

        if (componentCount == 0)
        {
            sb.AppendLine("            action(ids);");
        }
        else
        {
            var iterateArgs = string.Join(", ", Enumerable.Range(0, componentCount).Select(i => $"c{i}"));
            sb.AppendLine($"            action(ids, {iterateArgs});");
        }
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();

        // ForEach method
        sb.AppendLine("    public void ForEach(ForEachDelegate action)");
        sb.AppendLine("    {");
        sb.AppendLine("        var archetypes = _archetypeQuery.Run();");
        sb.AppendLine();
        sb.AppendLine("        foreach (Archetype archetype in archetypes)");
        sb.AppendLine("        {");
        sb.AppendLine("            World world = archetype.World;");
        sb.AppendLine("            var entityIds = archetype.GetEntityIds();");
        for (int i = 0; i < componentCount; i++)
        {
            sb.AppendLine($"            archetype.TryGetColumnSpan(out Span<T{i}> c{i});");
        }
        sb.AppendLine();
        sb.AppendLine("            for (int i = 0; i < entityIds.Length; i++)");
        sb.AppendLine("            {");
        sb.AppendLine("                var entity = Entity.Create(world, entityIds[i]);");

        if (componentCount == 0)
        {
            sb.AppendLine("                action(entity);");
        }
        else
        {
            var forEachArgs = string.Join(string.Empty, Enumerable.Range(0, componentCount)
                .Select(i => $", ref c{i}[i]"));
            sb.AppendLine($"                action(entity{forEachArgs});");
        }
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine("    }");

        sb.AppendLine("}");
    }

    private static void EmitQueryBuilderType(StringBuilder sb, int componentCount)
    {
        var generics = GenericArgs(componentCount);

        sb.AppendLine($"public struct QueryBuilder{generics}");
        EmitWhereClauses(sb, componentCount);
        sb.AppendLine("{");
        sb.AppendLine("    private RawQueryBuilder _builder;");
        sb.AppendLine();
        sb.AppendLine($"    internal QueryBuilder(RawQueryBuilder builder)");
        sb.AppendLine("    {");
        sb.AppendLine("        _builder = builder;");
        sb.AppendLine("    }");
        sb.AppendLine();

        sb.AppendLine($"    public QueryBuilder{generics} With<TExtra>() where TExtra : unmanaged");
        sb.AppendLine("    {");
        sb.AppendLine("        _builder.With<TExtra>();");
        sb.AppendLine("        return this;");
        sb.AppendLine("    }");
        sb.AppendLine();

        sb.AppendLine($"    public QueryBuilder{generics} Without<TExclude>() where TExclude : unmanaged");
        sb.AppendLine("    {");
        sb.AppendLine("        _builder.Without<TExclude>();");
        sb.AppendLine("        return this;");
        sb.AppendLine("    }");
        sb.AppendLine();

        sb.AppendLine($"    public Query{generics} Build()");
        sb.AppendLine("    {");
        sb.AppendLine("        var query = _builder.Build();");
        sb.AppendLine($"        return new Query{generics}(query);");
        sb.AppendLine("    }");
        sb.AppendLine("}");
    }

    private static void EmitSystemRegistration(StringBuilder sb, int componentCount)
    {
        var generics = GenericArgs(componentCount);

        sb.AppendLine($"public readonly struct SystemRegistration{generics}");
        EmitWhereClauses(sb, componentCount);
        sb.AppendLine("{");
        sb.AppendLine("    private readonly World _world;");
        sb.AppendLine($"    private readonly Query{generics} _query;");
        sb.AppendLine();
        sb.AppendLine($"    internal SystemRegistration(World world, Query{generics} query)");
        sb.AppendLine("    {");
        sb.AppendLine("        _world = world;");
        sb.AppendLine("        _query = query;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    public void ForEach(Query{generics}.ForEachDelegate action)");
        sb.AppendLine("    {");
        sb.AppendLine($"        var system = new SystemForEachWrapper{generics}(_query, action);");
        sb.AppendLine("        WorldExtensions.AddSystem(_world, system);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    public void Iterate(Query{generics}.IterateArchetypesDelegate action)");
        sb.AppendLine("    {");
        sb.AppendLine($"        var system = new SystemIterateWrapper{generics}(_query, action);");
        sb.AppendLine("        WorldExtensions.AddSystem(_world, system);");
        sb.AppendLine("    }");
        sb.AppendLine("}");
    }

    private static void EmitSystemWrappers(StringBuilder sb, int componentCount)
    {
        var generics = GenericArgs(componentCount);

        // ForEach wrapper
        sb.AppendLine($"internal sealed class SystemForEachWrapper{generics} : IWorldSystem");
        EmitWhereClauses(sb, componentCount);
        sb.AppendLine("{");
        sb.AppendLine($"    private readonly Query{generics} _query;");
        sb.AppendLine($"    private readonly Query{generics}.ForEachDelegate _action;");
        sb.AppendLine();
        sb.AppendLine($"    internal SystemForEachWrapper(Query{generics} query, Query{generics}.ForEachDelegate action)");
        sb.AppendLine("    {");
        sb.AppendLine("        _query = query;");
        sb.AppendLine("        _action = action;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    public void Execute(ref WorldSystemContext context)");
        sb.AppendLine("    {");
        sb.AppendLine("        _query.ForEach(_action);");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();

        // Iterate wrapper
        sb.AppendLine($"internal sealed class SystemIterateWrapper{generics} : IWorldSystem");
        EmitWhereClauses(sb, componentCount);
        sb.AppendLine("{");
        sb.AppendLine($"    private readonly Query{generics} _query;");
        sb.AppendLine($"    private readonly Query{generics}.IterateArchetypesDelegate _action;");
        sb.AppendLine();
        sb.AppendLine($"    internal SystemIterateWrapper(Query{generics} query, Query{generics}.IterateArchetypesDelegate action)");
        sb.AppendLine("    {");
        sb.AppendLine("        _query = query;");
        sb.AppendLine("        _action = action;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    public void Execute(ref WorldSystemContext context)");
        sb.AppendLine("    {");
        sb.AppendLine("        _query.Iterate(_action);");
        sb.AppendLine("    }");
        sb.AppendLine("}");
    }

    private static void EmitWorldSystemExtensions(StringBuilder sb)
    {
        sb.AppendLine("public static class WorldSystemExtensions");
        sb.AppendLine("{");

        for (int componentCount = 1; componentCount <= MaxComponents; componentCount++)
        {
            var generics = GenericArgs(componentCount);
            var whereClauses = string.Join(" ", Enumerable.Range(0, componentCount).Select(i => $"where T{i} : unmanaged"));

            sb.AppendLine($"    public static SystemRegistration{generics} System{generics}(this IWorld world) {whereClauses}");
            sb.AppendLine("    {");
            sb.AppendLine("        var concrete = (World)world;");
            sb.AppendLine("        var builder = RawQueryBuilder.For(concrete);");
            for (int i = 0; i < componentCount; i++)
            {
                sb.AppendLine($"        builder.Add<T{i}>();");
            }
            sb.AppendLine("        var archetypeQuery = builder.Build();");
            sb.AppendLine($"        var typedQuery = new Query{generics}(archetypeQuery);");
            sb.AppendLine($"        return new SystemRegistration{generics}(concrete, typedQuery);");
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        sb.AppendLine("}");
    }

    private static void EmitDefineQuery(StringBuilder sb)
    {
        sb.AppendLine("public static partial class DefineQuery");
        sb.AppendLine("{");

        for (int componentCount = 0; componentCount <= MaxComponents; componentCount++)
        {
            var generics = GenericArgs(componentCount);
            var whereClauses = string.Join(" ", Enumerable.Range(0, componentCount).Select(i => $"where T{i} : unmanaged"));

            sb.AppendLine($"    public static QueryBuilder{generics} For{generics}(IWorld world) {whereClauses}");
            sb.AppendLine("    {");
            sb.AppendLine("        var concrete = (World)world;");
            sb.AppendLine("        var builder = RawQueryBuilder.For(concrete);");
            for (int i = 0; i < componentCount; i++)
            {
                sb.AppendLine($"        builder.Add<T{i}>();");
            }
            sb.AppendLine($"        return new QueryBuilder{generics}(builder);");
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        sb.AppendLine("}");
    }
}
