using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Axis.ECS.Generators;

[Generator]
public sealed class SimpleIncrementalGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Find static methods that also have [SystemSource]
        var methods = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) =>
                    node is MethodDeclarationSyntax m &&
                    m.Modifiers.Any(SyntaxKind.StaticKeyword) &&
                    m.AttributeLists.Count > 0,
                transform: static (ctx, _) =>
                {
                    var method = (IMethodSymbol)ctx.SemanticModel.GetDeclaredSymbol((MethodDeclarationSyntax)ctx.Node)!;
                    // Only keep if it has [SystemSource]
                    var hasAttr = method
    .GetAttributes()
    .Any(a => a.AttributeClass?.ToDisplayString() == "Axis.ECS.Generators.SystemSourceAttribute");
                    return hasAttr ? method : null;
                })
            .Where(m => m is not null)!;

        // Output file for every [SystemSource] method
        context.RegisterSourceOutput(methods, static (spc, method) =>
        {
            var ns = method.ContainingNamespace.ToDisplayString();
            var typeName = method.ContainingType.Name;
            var methodName = method.Name;

            var src = $@"
                // Auto-generated by SimpleIncrementalGenerator
                namespace {ns}
                {{
                    public static partial class {typeName}
                    {{
                        public static void Generated_{methodName}()
                        {{
                            System.Console.WriteLine(""Hello from generated: {methodName}"");
                        }}
                    }}
                }}
            ";
            spc.AddSource($"{typeName}_{methodName}.g.cs", src);
        });
    }
}