using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Axis.ECS.Generators;

[Generator]
public sealed class SimpleIncrementalGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Look for methods that have attributes and are static
        var methodDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) =>
                    node is MethodDeclarationSyntax method &&
                    method.AttributeLists.Count > 0 &&
                    method.Modifiers.Any(SyntaxKind.StaticKeyword),
                transform: static (ctx, _) =>
                {
                    var methodSymbol = (IMethodSymbol?)ctx.SemanticModel
                        .GetDeclaredSymbol((MethodDeclarationSyntax)ctx.Node);

                    if (methodSymbol == null)
                        return null;

                    // Only select methods marked [SystemSource]
                    var hasAttr = methodSymbol.GetAttributes()
                        .Any(a => a.AttributeClass?.ToDisplayString() ==
                                  "Axis.ECS.SystemSourceAttribute");

                    return hasAttr ? methodSymbol : null;
                })
            .Where(static m => m is not null)!;

        // For each valid method we found, generate a code file
        context.RegisterSourceOutput(methodDeclarations,
            static (spc, method) =>
            {
                GenerateForMethod(spc, method!);
            });
    }

    private static void GenerateForMethod(SourceProductionContext spc, IMethodSymbol method)
    {
        var @namespace = method.ContainingNamespace.ToDisplayString();
        var type = method.ContainingType;
        var typeName = type.Name;
        var methodName = method.Name;

        // Build up generated code
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine($"namespace {@namespace};");
        sb.AppendLine();

        // Respect original modifiers (public / internal etc.)
        var modifiers = GetTypeModifiers(type);
        var typeKind =
            type.TypeKind == TypeKind.Class ? "class" :
            type.TypeKind == TypeKind.Struct ? "struct" :
            "class";

        sb.AppendLine($"{modifiers} partial {typeKind} {typeName}");
        sb.AppendLine("{");

        sb.AppendLine($"    public static void Generated_{methodName}()");
        sb.AppendLine("    {");
        sb.AppendLine($"        System.Console.WriteLine(\"Inspecting method: {methodName}\");");

        foreach (var p in method.Parameters)
        {
            var modifier = p.RefKind switch
            {
                RefKind.Ref => "ref",
                RefKind.In => "in",
                RefKind.Out => "out",
                _ => "value"
            };

            sb.AppendLine(
                $"        System.Console.WriteLine(\"Param: {modifier} {p.Type.ToDisplayString()} {p.Name}\");");
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        spc.AddSource($"{typeName}_{methodName}.g.cs", sb.ToString());
    }

    private static string GetTypeModifiers(INamedTypeSymbol type)
    {
        var parts = new List<string>();

        switch (type.DeclaredAccessibility)
        {
            case Accessibility.Public:
                parts.Add("public");
                break;
            case Accessibility.Internal:
                parts.Add("internal");
                break;
            case Accessibility.Private:
                parts.Add("private");
                break;
            case Accessibility.Protected:
                parts.Add("protected");
                break;
            case Accessibility.ProtectedAndInternal:
                parts.Add("protected internal");
                break;
            case Accessibility.ProtectedOrInternal:
                parts.Add("private protected");
                break;
        }

        if (type.IsStatic)
            parts.Add("static");
        else
        {
            if (type.IsAbstract)
                parts.Add("abstract");
            if (type.IsSealed)
                parts.Add("sealed");
        }

        return string.Join(" ", parts);
    }
}