<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Axis.Collision</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Axis.Core/Axis.Core.csproj" />
    <ProjectReference Include="../Axis.ECS/Axis.ECS.csproj" />
  </ItemGroup>

</Project>
